parser: '@babel/eslint-parser'
env:
  browser: true
  es6: true
extends:
  - "eslint:recommended"
  - "prettier"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
parserOptions:
  ecmaVersion: 6
  sourceType: module
globals:
  beforeAll: true
  describe: true
  expect: true
  global: true
  insights: true
  it: true
  mount: true
  process: true
  render: true
  shallow: true
  React: true
rules:
  no-console: 1
  no-async-promise-executor: 0
  no-misleading-character-class: 0
  no-prototype-builtins: 0
  no-shadow-restricted-names: 0
  no-useless-catch: 0
  no-dupe-else-if: 0
  no-import-assign: 0
  no-setter-return: 0
  require-atomic-updates: 0
  array-bracket-spacing: 2
  jsx-quotes: [2, 'prefer-double']
  react/boolean-prop-naming: 2
  react/no-children-prop: 2
  react/display-name: 0
  react/no-danger: 2
  react/no-deprecated: 2
  react/no-direct-mutation-state: 2
  react/no-typos: 2
  react/no-unused-prop-types: 2
  react/no-unused-state: 2
  react/prefer-es6-class: 2
  react/prefer-read-only-props: 2
  react/require-render-return: 2
  react/state-in-constructor: 2
  react/static-property-placement: 2
  react/style-prop-object: 2
  react/jsx-boolean-value: 2
  react/jsx-handler-names: 2
  react/sort-comp:
    [
      2,
      {
        order:
          [
            "static-methods",
            "lifecycle",
            "everything-else",
            "/^handle.+$/",
            "render",
          ],
      },
    ]
  comma-dangle: 2
  comma-spacing:
    - 2
    - after: true
  comma-style: 2
  camelcase: [2, { properties: never }]
  curly:
    - error
    - all
  dot-notation: 2
  eol-last: 2
  eqeqeq: 2
  func-names:
    - error
    - never
  indent:
    - error
    - 4
    - SwitchCase: 1
      MemberExpression: 0
      ImportDeclaration: 1
      ObjectExpression: 1
  key-spacing: 2
  keyword-spacing: 2
  linebreak-style:
    - error
    - unix
  max-len:
    - 2
    - 130
  new-cap: [2, { "capIsNewExceptions": ["Immutable"] }]
  no-bitwise: 2
  no-caller: 2
  no-mixed-spaces-and-tabs: 2
  no-multiple-empty-lines:
    - error
    - max: 1
  no-trailing-spaces: 2
  no-use-before-define:
    - error
    - functions: false
  no-undef: 2
  no-unused-vars: 1
  no-var: 2
  no-with: 2
  object-shorthand: 2
  object-curly-spacing:
    - error
    - always
  one-var:
    - error
    - never
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: block-like
      next: "*"
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  space-before-blocks: 2
  space-in-parens: 2

  space-infix-ops: 2
  space-unary-ops:
    - error
    - words: false
      nonwords: false
  vars-on-top: 2
  wrap-iife: 2
  yoda:
    - error
    - never
